Tarea3 B66958
UCR-Paraiso-Lenguajes/lenguajes24 pull request #259
Opened 2024-05-07 03:13 UTC by EisenheimDiego

2024-05-07 14:24 UTC, cguillencr requested changes
Mucho mejor que los otros commits... Pero te faltaron los UT

2024-05-07 14:24 UTC, cguillencr commented on B66958/Labs/Lab7/Core/Models/Category.cs
> +    public List<Category> GetCategories()
Ienumerable

2024-05-07 14:24 UTC, cguillencr commented on B66958/Labs/ejemploNext/my-nextjs-app/src/app/page.tsx
> +        console.log("category was 0")
quitar console log

2024-05-07 18:04 UTC, EisenheimDiego commented on B66958/Labs/Lab7/Core/Models/Category.cs
> +    public List<Category> GetCategories()
Se realizó el cambio.

2024-05-07 18:04 UTC, EisenheimDiego commented on B66958/Labs/ejemploNext/my-nextjs-app/src/app/page.tsx
> +        console.log("category was 0")
Se me fue jaja. Listo, cambiado.

2024-05-07 22:20 UTC, cguillencr commented on B66958/Labs/Lab7/Core/Models/Category.cs
> +    public static Category Build(int id, string name)
Por que ocupamos un static en lugar de llamar al contructor directamente ?

2024-05-07 22:22 UTC, cguillencr requested changes
Falta algun UT que pruebe la funcionalidad de filtrar categorias y sus asserts

2024-05-08 03:17 UTC, EisenheimDiego commented on B66958/Labs/Lab7/Core/Models/Category.cs
> +    public static Category Build(int id, string name)
La idea es tener un método que construye instancias de Category. Para no validar en el constructor, mejor utilizo ese método. Si eventualmente crecen las validaciones, el método Build se encarga de ellas.

2024-05-09 01:12 UTC, cguillencr approved these changes

2024-05-09 17:49 UTC, merged

2024-05-09 20:05 UTC, cguillencr commented on B66958/Labs/Lab7/Core/Data/Db.cs
> +                                CategoryId = reader.GetInt32(5)
Aquí debería se cargarse el obj categoria a la memoria

2024-05-10 18:22 UTC, EisenheimDiego commented on B66958/Labs/Lab7/Core/Models/Category.cs
> +    public static Category Build(int id, string name)
Porque puede existir un segundo método Builder, que crea instancias para otro propósito, y en ese caso, las validaciones pueden cambiar. Entonces mi idea es que cada método Builder se encargue de validar lo que ocupa él, para crear la instancia.