Tarea3C12599
UCR-Paraiso-Lenguajes/lenguajes24 pull request #260
Opened 2024-05-09 09:01 UTC by Marianoda20027

Tarea3

2024-05-09 15:24 UTC, cguillencr requested changes

2024-05-09 15:24 UTC, cguillencr commented on C12599/lab10/Api/Core/models/Categories.cs
> +    public class Category
struct

2024-05-09 15:24 UTC, cguillencr commented on C12599/lab10/Api/Core/models/Products.cs
> +                Console.WriteLine("Invalid product data row: Insufficient columns.");
Mal uso de errores... deberian ser throw exception

2024-05-09 15:24 UTC, cguillencr commented on C12599/lab10/Api/storeapi/Controllers/ProductsController.cs
> +        public IActionResult GetProducts([FromQuery] string category)
Esto debería recibir el categoria Id y no el nombre para hacer la búsqueda más eficiente

2024-05-10 03:36 UTC, Marianoda20027 commented on C12599/lab10/Api/storeapi/Controllers/ProductsController.cs
> +        public IActionResult GetProducts([FromQuery] string category)
Corregido Profe

2024-05-10 03:37 UTC, Marianoda20027 commented on C12599/lab10/Api/Core/models/Products.cs
> +                Console.WriteLine("Invalid product data row: Insufficient columns.");
Corregido Profe

2024-05-10 03:44 UTC, Marianoda20027 commented
Correcciones hechas ya filtra por categoría

2024-05-10 20:06 UTC, cguillencr requested changes

2024-05-10 20:06 UTC, cguillencr commented on C12599/lab10/Api/Core/models/Categories.cs
> +        public int Id { get; set; }
reducir visibilidad de los sets

2024-05-10 20:06 UTC, cguillencr commented on C12599/lab10/Api/Core/models/Categories.cs
> +  public int GetCategoryId(string categoryId)
No tiene sentido hacer un metodo que pide el id y retorna el id

2024-05-10 20:06 UTC, cguillencr commented on C12599/lab10/laboratorio6/laboratorio6/app/page.tsx
> +    const response = await fetch(`https://localhost:7043/api/Products/GetProducts?category=${categoryId}`);
no cumple con el standar restfull

2024-05-10 20:56 UTC, Marianoda20027 commented
Correcciones realizadas

2024-05-10 21:10 UTC, Marianoda20027 commented
Correcciones realizadas

2024-05-11 05:19 UTC, closed without merging