Primer Avance - Estructura de la Lógica
UCR-Paraiso-Lenguajes/lenguajes24 pull request #262
Opened 2024-05-09 18:20 UTC by Alvaro499

Profe, seria mas que todo para ir viendo la estructura del código y ver mas o menos como lo llevo.
Todavía no esta funcional ni nada de eso

2024-05-09 20:03 UTC, cguillencr requested changes
Falta los UT

2024-05-09 20:03 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Product.cs
> +        public int idCategorie {get;set;}
Producto debería tener elatributo categoria, no IDCategoría.  Ese match se debe hacer cuando se estan cargando los productos a memoria

2024-05-09 20:03 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Products.cs
> +    public List<Product> productsFromStore {get;}
Ienumerable

2024-05-09 20:03 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Products.cs
> +    public ArrayList categoriesFromStore {get;}
mejor List que ArrayList

2024-05-09 20:03 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Products.cs
> +    public Dictionary<int, List<Product>> productsByCategorire {get;private set;}
No parece usarse en el código

2024-05-09 20:03 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Store.cs
>          public List<Product> Products { get; private set; }
El get debe retornar Ienumerable

2024-05-09 20:03 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Store.cs
> +        public ArrayList StoreCategories {get; private set;}
Los mismo aquí

2024-05-09 20:03 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Store.cs
> +        private ArrayList AssignCategoriesToProducts(){
List y tipada

2024-05-09 20:03 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Store.cs
> +                    idCategorie = 1
Debería mandarse la categoría como tal y no el id

2024-05-09 20:03 UTC, cguillencr commented on C27507/C27507_Lab7/MyStoreAPI/Controllers/ProductsController.cs
> +        public IActionResult returnFilteredProducts(id specificCategorie){
specificCategorie typo

2024-05-10 19:35 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Category.cs
> +        public int id {get;set;}
creo que los set No debería ser públicos

2024-05-10 19:36 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Products.cs
> +            throw new ArgumentException($"{nameof(categoriesFromStore)} no es valido" );
tilde

2024-05-10 19:37 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Store.cs
> +            mockDataAsync(Products);
Esto de la mock data solo debe pasar en desarrollo

2024-05-10 19:38 UTC, cguillencr commented on C27507/C27507_Lab7/MyStoreAPI/Controllers/ProductsController.cs
> +        public IActionResult returnFilteredProducts(int specificCategorie){
RESTfull standar no debe llevar verbos en la url

2024-05-10 19:38 UTC, cguillencr commented on C27507/C27507_Lab7/MyStoreAPI/Controllers/ProductsController.cs
> +        [HttpGet]
Falta la integración con el FE

2024-05-10 20:03 UTC, Alvaro499 commented on C27507/C27507_Lab7/Core/Models/Store.cs
> +            mockDataAsync(Products);
Profe ese mockData es solo para insertar ventas automáticas

2024-05-11 18:02 UTC, cguillencr requested changes

2024-05-11 18:02 UTC, cguillencr commented on C27507/C27507_Lab1/nodeJS_Lab3/nextjs-dashboard/app/page.tsx
> +                <Dropdown.Item eventKey="0">Todos los productos:</Dropdown.Item>
las categorias vienen del BE... No estan equemados en el FE

2024-05-11 18:02 UTC, cguillencr commented on C27507/C27507_Lab1/nodeJS_Lab3/nextjs-dashboard/app/src/api/get-post-api.tsx
> +        const directionAPI = `https://localhost:7161/api/Products/store/products/category?category=${encodeURIComponent(idCategory)}`;
no ocupa /category

2024-05-11 18:02 UTC, cguillencr commented on C27507/C27507_Lab7/Core/Models/Categories.cs
> +            CategoryList = new List<Category>(){
tíldes

2024-05-11 18:27 UTC, cguillencr approved these changes

2024-05-15 18:08 UTC, merged