Tarea3 c02231
UCR-Paraiso-Lenguajes/lenguajes24 pull request #263
Opened 2024-05-09 18:28 UTC by Lani6

Falta UT y el diccionario de categorias

2024-05-09 20:39 UTC, cguillencr requested changes

2024-05-09 20:39 UTC, cguillencr commented on C02231/Store/Lab7/Core/Database/StoreDB.cs
> +            IdCategory = 3,
Los prodctos deberían llevar la intancia de la categoría

2024-05-09 20:39 UTC, cguillencr commented on C02231/Store/Lab7/Core/Model/Product.cs
> +    public int IdCategory { get; set; }
Debería se categoría

2024-05-10 19:55 UTC, cguillencr approved these changes

2024-05-10 19:55 UTC, cguillencr commented on C02231/Store/Lab7/Core/Model/Product.cs
> +    public int Quantity { get; set; }
Estos set no deberían ser privados ?

2024-05-11 18:09 UTC, cguillencr requested changes
Revisar todos los comments https://github.com/UCR-Paraiso-Lenguajes/lenguajes24/commit/4007b5741f3b6c9af496a31c3e70fdf76f4d0805

2024-05-11 18:18 UTC, Lani6 commented on C02231/Store/Lab7/Core/Model/Product.cs
> +    public int Quantity { get; set; }
Cambiados

2024-05-12 17:38 UTC, cguillencr approved these changes

2024-05-15 00:48 UTC, merged