Tarea 3
UCR-Paraiso-Lenguajes/lenguajes24 pull request #264
Opened 2024-05-09 19:01 UTC by JeanZQ

2024-05-09 20:43 UTC, cguillencr requested changes
No veo endpoint para filtrar los productos por categorías, ni los unit  test

2024-05-09 20:43 UTC, cguillencr commented on C18780/backend/StoreApi/Api/Controllers/CategoryController.cs
> +        public Categories GetCategoryById(Guid uuid)
validaciones

2024-05-09 20:43 UTC, cguillencr commented on C18780/backend/StoreApi/Api/Controllers/CategoryController.cs
> +        public Categories GetCategoryByName(string name)
validaciones

2024-05-09 20:43 UTC, cguillencr commented on C18780/backend/StoreApi/Api/Controllers/StoreController.cs
> +            var taxPercentage = 13;
Esto debe ser un Const y estar en Logic

2024-05-09 20:43 UTC, cguillencr commented on C18780/backend/Core/Models/Category.cs
debe ser un struct

2024-05-09 21:38 UTC, JeanZQ commented on C18780/backend/StoreApi/Api/Controllers/CategoryController.cs
> +        public Categories GetCategoryById(Guid uuid)
Estan en el handler

2024-05-09 21:48 UTC, JeanZQ commented on C18780/backend/StoreApi/Api/Controllers/CategoryController.cs
> +        public Categories GetCategoryByName(string name)
Estan en el handler

2024-05-09 21:48 UTC, JeanZQ commented on C18780/backend/StoreApi/Api/Controllers/StoreController.cs
> +            var taxPercentage = 13;
Donde el Logic?

2024-05-09 21:48 UTC, JeanZQ commented on C18780/backend/Core/Models/Category.cs
Categories es el struct

2024-05-10 19:56 UTC, cguillencr commented on C18780/backend/StoreApi/Api/Controllers/StoreController.cs
> +            var taxPercentage = 13;
Store por ejemplo... O hacer una clase de settings

2024-05-10 20:00 UTC, cguillencr requested changes

2024-05-10 20:00 UTC, cguillencr commented on C18780/backend/Core/Cache/CategoriesCache.cs
> +        public static List<Categories> _categories { get; set; }
get Ienumerable
set debe ser privado

2024-05-10 20:00 UTC, cguillencr commented on C18780/backend/Core/Cache/CategoriesCache.cs
> +        public Categories GetCategoryByName(string name)
validaciones

2024-05-10 20:00 UTC, cguillencr commented on C18780/backend/Core/Cache/ProductsCache.cs
> +        public static IEnumerable<Product> Products { get; set; }
reuducir visibilidad del set

2024-05-10 20:00 UTC, cguillencr commented on C18780/backend/Core/Models/Products.cs
> +        public IEnumerable<Product> products {get; set;}
reducir visibilidad del set

2024-05-10 20:00 UTC, cguillencr commented on C18780/primer trabajo/demo6/nextjs-dashboard/app/api/http.initialStore.ts
> +        const res = await fetch(`https://localhost:7099/api/Store/getStore?category=${category}`);
utl no cumple con restfull

2024-05-12 01:03 UTC, JeanZQ commented on C18780/backend/Core/Models/Products.cs
> +        public IEnumerable<Product> products {get; set;}
Termine borrando Products jajaja

2024-05-12 01:07 UTC, JeanZQ commented on C18780/backend/Core/Cache/CategoriesCache.cs
> +        public static List<Categories> _categories { get; set; }
Cuando se levanta la aplicacion y se trae todas las categorias de la db, con set private o internal, me da error

2024-05-12 17:47 UTC, cguillencr approved these changes

2024-05-12 19:04 UTC, merged