Tarea3_Lista-Faltan_UT
UCR-Paraiso-Lenguajes/lenguajes24 pull request #265
Opened 2024-05-10 06:10 UTC by ItsChaco26

2024-05-10 17:27 UTC, cguillencr requested changes

2024-05-10 17:27 UTC, cguillencr commented on C22037/Tarea3/Core/Business/CategoryLogic.cs
> +        private static Dictionary<int, Category.CategorySt> categoryById;
Esta variable parece código muerto no la usas para nada más, solo la cargas y desperdicia  memoria

2024-05-10 17:27 UTC, cguillencr commented on C22037/Tarea3/Core/Business/CategoryLogic.cs
> +        public CategoryLogic(Category.CategorySt[] categories, IEnumerable<Product> products)
validar lenght cero

2024-05-10 17:27 UTC, cguillencr commented on C22037/Tarea3/Core/Business/CategoryLogic.cs
> +            if (productsByCategoryId.ContainsKey(id))
Usar try toGet para optimizar este código

2024-05-10 17:27 UTC, cguillencr commented on C22037/Tarea3/Core/Models/Product.cs
> +        public Category.CategorySt Category { get; private set; }
No está mal pero pude recibir el Obj de Categoría directamente

2024-05-10 17:27 UTC, cguillencr commented on C22037/Tarea3/Core/Database/StoreDB.cs
> +                CREATE TABLE IF NOT EXISTS products (
a todos les falta el not null

2024-05-10 17:27 UTC, cguillencr commented on C22037/Tarea3/Core/Database/StoreDB.cs
> +                    category int
puede ser un enum en mysql para mejorar la explicación del código

2024-05-10 17:27 UTC, cguillencr commented on C22037/Tarea3/Core/Models/Store.cs
> +        private Store(IEnumerable<Product> products, int taxPercentage)
validar lista en 0

2024-05-10 17:27 UTC, cguillencr commented on C22037/Tarea3/TodoApi/TodoApi.http
> +GET {{TodoApi_HostAddress}}/weatherforecast/
esto no va

2024-05-10 17:27 UTC, cguillencr commented on C22037/Tarea3/TodoApi/appsettings.json
> +    "MyDatabase": "Server=localhost;Port=3407;Database=store;Uid=root;Pwd=123456;"
Esto va en [appsettings.Development.json](https://github.com/UCR-Paraiso-Lenguajes/lenguajes24/pull/265/files#diff-f69343061d55fddbbc9a466ffad34cc2b1604f0d54ab98e252c658f17824328d)

2024-05-10 19:26 UTC, ItsChaco26 commented on C22037/Tarea3/Core/Models/Product.cs
> +        public Category.CategorySt Category { get; private set; }
Profe es que dentro de Category hay varias cosas, como el sort o las categorías, el struct en sí sería CategorySt

2024-05-10 19:27 UTC, ItsChaco26 commented on C22037/Tarea3/Core/Database/StoreDB.cs
> +                    category int
Profe, entonces tendría que cargar el id y nombre en category? Es que por ahora estaba enviando solo el id y que category se encargara de asociarlo a un nombre

2024-05-11 18:21 UTC, cguillencr requested changes

2024-05-11 18:21 UTC, cguillencr commented on C22037/Tarea3/Core/Database/StoreDB.cs
> +                        var category = new Category();
Se esta creando una instancia de categories por cada ietración. Esto debe sacarse de aquí o ser un singleton

2024-05-11 18:21 UTC, cguillencr commented on C22037/Tarea3/Core/Models/Category.cs
> +    public class Category
Categories

2024-05-11 18:21 UTC, cguillencr commented on C22037/Tarea3/Core/Models/Category.cs
> +            public int Id { get; set; }
reducir vsibilidad de los sets

2024-05-11 18:21 UTC, cguillencr commented on C22037/Tarea3/Core/Models/Category.cs
> +    public class Category
Categories

2024-05-11 18:21 UTC, cguillencr commented on C22037/Tarea3/my-app/app/admin/init/page.tsx
> +            const response = await fetch(`https://localhost:7067/api/Sale?date=${formattedDate}`);
ulrs en minuscula

2024-05-11 18:21 UTC, cguillencr commented on C22037/Tarea3/my-app/app/page.tsx
> +        const response = await fetch(`https://localhost:7067/api/Store`);
minusculas

2024-05-11 19:47 UTC, closed without merging