RevisiónTarea_C27529
UCR-Paraiso-Lenguajes/lenguajes24 pull request #268
Opened 2024-05-10 20:16 UTC by chmod2314

En base a la consulta del jueves fue como procedí con la implementación

2024-05-10 20:34 UTC, chmod2314 commented
Faltan los UT

2024-05-11 18:15 UTC, cguillencr requested changes

2024-05-11 18:15 UTC, cguillencr commented on C27529/Lab10/Core/Models/Category.cs
> +        public List<ProductCategory> GetCategories()
Ienumerable

2024-05-11 18:15 UTC, cguillencr commented on C27529/Lab10/Core/Models/Category.cs
> +        public List<ProductCategory> GetCategoryNames()
Ienumerable

2024-05-11 18:15 UTC, cguillencr commented on C27529/Lab10/Core/Models/Category.cs
> +            new ProductCategory { Id = 2, Name = "Controles" },
Tíldes

2024-05-11 18:15 UTC, cguillencr commented on C27529/Lab10/Core/Models/Product.cs
> +    public int Category { get; set; }
debeser un obj Categoria

2024-05-11 18:15 UTC, cguillencr commented on C27529/Lab10/Core/Models/Store.cs
> +        public List<Category.ProductCategory> CategoriesNames { get; private set; }
los get debe retonar Ienumerable

2024-05-11 18:15 UTC, cguillencr commented on C27529/Lab10/Core/Models/Store.cs
> +            Store.Instance = new Store(productsTask.Result, 13);
13 debe ser un Const

2024-05-11 18:15 UTC, cguillencr commented on C27529/Lab10/next/nextjs-dashboard/app/components/Products.jsx
> +      const response = await fetch(`https://localhost:7280/api/Store`);
urls en minuscula

2024-05-11 18:15 UTC, cguillencr commented on C27529/Lab10/next/nextjs-dashboard/app/components/Products.jsx
> +      const response = await fetch(`https://localhost:7280/api/Store/products?category=${category}`);
url en minusculas

2024-05-11 18:15 UTC, cguillencr commented on C27529/Lab10/next/nextjs-dashboard/app/components/Products.jsx
> +      console.error('Failed to fetch data:', error);
quitar console log

2024-05-11 22:49 UTC, chmod2314 commented on C27529/Lab10/Core/Models/Product.cs
> +    public int Category { get; set; }
Profe y en la BD si se guarda un int? se relaciona cuando se le envian los datos de la BD?

2024-05-12 17:45 UTC, cguillencr reviewed
No estan los UT

2024-05-12 17:45 UTC, cguillencr commented on C27529/Lab10/Core/Models/Category.cs
> +            new ProductCategory { Id = 2, Name = "Controles" },
Audífonos

2024-05-12 17:46 UTC, cguillencr commented on C27529/Lab10/Core/Models/Product.cs
> +    public int Category { get; set; }
correcto en la bd se guarda como db y en memoria se usa como objeto

2024-05-12 17:46 UTC, cguillencr commented on C27529/Lab10/next/nextjs-dashboard/app/components/Products.jsx
> +      const response = await fetch(`https://localhost:7280/api/Store/products?category=${category}`);
falta

2024-05-12 17:46 UTC, cguillencr commented on C27529/Lab10/next/nextjs-dashboard/app/components/Products.jsx
> +      console.error('Failed to fetch data:', error);
falta

2024-05-16 15:15 UTC, cguillencr approved these changes

2024-05-16 23:58 UTC, merged