Examen1 B66958
UCR-Paraiso-Lenguajes/lenguajes24 pull request #275
Opened 2024-05-14 19:24 UTC by EisenheimDiego

2024-05-16 02:14 UTC, cguillencr requested changes

2024-05-16 02:14 UTC, cguillencr commented on B66958/Labs/Lab7/Core/Business/TreeSearchBusiness.cs
> +    public Product Product { get; set; }
reducir visibilidad de los sets

2024-05-16 02:14 UTC, cguillencr commented on B66958/Labs/Lab7/Core/Business/TreeSearchBusiness.cs
> +    {
validaciones de query

2024-05-16 02:14 UTC, cguillencr commented on B66958/Labs/Lab7/Core/Business/TreeSearchBusiness.cs
> +        if (node.Product.Name.Contains(query) || node.Product.Description.Contains(query))
variable explicativa

2024-05-16 20:55 UTC, EisenheimDiego commented on B66958/Labs/Dockerfile
Se eliminó. No era parte de esta solución.

2024-05-16 20:56 UTC, EisenheimDiego commented on B66958/Labs/Lab7/Core/Business/TreeSearchBusiness.cs
> +    public Product Product { get; set; }
Realicé el cambio.

2024-05-16 20:56 UTC, EisenheimDiego commented on B66958/Labs/Lab7/Core/Business/TreeSearchBusiness.cs
> +    {
Agregué la validación.

2024-05-16 20:56 UTC, EisenheimDiego commented on B66958/Labs/Lab7/Core/Business/TreeSearchBusiness.cs
> +        if (node.Product.Name.Contains(query) || node.Product.Description.Contains(query))
Lo cambié por una variable descriptiva.

2024-05-18 14:40 UTC, cguillencr approved these changes

2024-05-18 14:44 UTC, merged