Lab12 B66958
UCR-Paraiso-Lenguajes/lenguajes24 pull request #300
Opened 2024-05-26 21:57 UTC by EisenheimDiego

2024-05-29 23:43 UTC, cguillencr requested changes

2024-05-29 23:43 UTC, cguillencr commented on .github/workflows/B66958.yml
> +    branches: [ "B66958_DevOps" ]
dejemoslo solo el carnet B66958

2024-05-29 23:47 UTC, cguillencr requested changes
faltan los UT

2024-05-30 15:03 UTC, cguillencr requested changes

2024-05-30 15:03 UTC, cguillencr commented on .github/workflows/B66958.yml
> +    branches: [ "Lab12_B66958" ]
solo carnet

2024-05-30 15:03 UTC, cguillencr commented on B66958/Labs/Lab7/Core/Models/User.cs
> +    public string Password { get; set; }
reducir visbilidad set

2024-05-30 15:03 UTC, cguillencr commented on B66958/Labs/Lab7/Core/Models/User.cs
> +    public List<UserAuth> Development { get; set; }
reducir vibilidad set
Get return Ienumerable

2024-05-31 13:47 UTC, cguillencr approved these changes

2024-05-31 17:53 UTC, EisenheimDiego commented on .github/workflows/B66958.yml
> +    branches: [ "Lab12_B66958" ]
Se cambió.

2024-05-31 17:53 UTC, EisenheimDiego commented on B66958/Labs/Lab7/Core/Models/User.cs
> +    public string Password { get; set; }
Se corrigió.

2024-05-31 17:54 UTC, EisenheimDiego commented on B66958/Labs/Lab7/Core/Models/User.cs
> +    public List<UserAuth> Development { get; set; }
Lo pasé IEnumerable, pero si reduzco la visibilidad del set, entonces a la hora de leer el appsettings, no puede asignar los valores leídos a la variable, entonces nunca va a encontrar usuarios para el login.

2024-06-01 15:20 UTC, cguillencr approved these changes

2024-06-05 23:12 UTC, merged