Lab12_C27507 (No completo)
UCR-Paraiso-Lenguajes/lenguajes24 pull request #301
Opened 2024-05-27 06:38 UTC by Alvaro499

Profe, resulta que obtengo el token en el UI, pero al momento de hacer los Test, nunca lo obtiene, las respuestas siempre son nulas

2024-05-27 21:50 UTC, cguillencr commented
> Profe, resulta que obtengo el token en el UI, pero al momento de hacer los Test, nunca lo obtiene, las respuestas siempre son nulas: ![image](https://private-user-images.githubusercontent.com/71684805/333993531-ce301661-d1a0-466e-a932-c34595712671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NDY5MTUsIm5iZiI6MTcxNjg0NjYxNSwicGF0aCI6Ii83MTY4NDgwNS8zMzM5OTM1MzEtY2UzMDE2NjEtZDFhMC00NjZlLWE5MzItYzM0NTk1NzEyNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDIxNTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5OGMwNGM0YjNjNzZhZWI4MzVlMTEwNTVjNWE2NmE2NzliOTcwYTQwMDVhMWJkNjI1NzFjYTlmMWYzNzAwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ahgp__V-EF_kZLoXuwwFGvPXIUGSzysekiVPyqrNSsM)

Y si lo debugeas por dónde pasa ?

2024-05-29 17:40 UTC, Alvaro499 commented
> > Profe, resulta que obtengo el token en el UI, pero al momento de hacer los Test, nunca lo obtiene, las respuestas siempre son nulas: ![image](https://private-user-images.githubusercontent.com/71684805/333993531-ce301661-d1a0-466e-a932-c34595712671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NDY5MTUsIm5iZiI6MTcxNjg0NjYxNSwicGF0aCI6Ii83MTY4NDgwNS8zMzM5OTM1MzEtY2UzMDE2NjEtZDFhMC00NjZlLWE5MzItYzM0NTk1NzEyNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDIxNTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5OGMwNGM0YjNjNzZhZWI4MzVlMTEwNTVjNWE2NmE2NzliOTcwYTQwMDVhMWJkNjI1NzFjYTlmMWYzNzAwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ahgp__V-EF_kZLoXuwwFGvPXIUGSzysekiVPyqrNSsM)
> 
> Y si lo debugeas por dónde pasa ?

Profe, no lo pude debugguear por un problema con launch.json, pero igual lo resolví
![image](https://github.com/UCR-Paraiso-Lenguajes/lenguajes24/assets/71684805/229c8932-360d-4feb-ab02-004fdb62dee5)

No le estaba indicando el tipo de ambiente a la instancia de authController en los test

2024-05-30 00:08 UTC, cguillencr requested changes

2024-05-30 14:31 UTC, cguillencr requested changes
Algo que no veo en tu PR es que valides que el token aun siga activo antes de hacer los fetch

2024-05-30 14:45 UTC, Alvaro499 commented
> Algo que no veo en tu PR es que valides que el token aun siga activo antes de hacer los fetch

Ok, si actualmente solo se está verificando al cargar la página, ya lo agrego

2024-05-31 05:08 UTC, Alvaro499 commented
> Algo que no veo en tu PR es que valides que el token aun siga activo antes de hacer los fetch

YA FUE CORREGIDO

2024-05-31 13:48 UTC, cguillencr requested changes

2024-05-31 13:48 UTC, cguillencr commented on C27507/C27507_Lab1/nodeJS_Lab3/nextjs-dashboard/app/src/api/get-post-api.tsx
> +        console.log(tokenFormat);
quitar logs

2024-06-01 15:43 UTC, cguillencr approved these changes

2024-06-05 15:54 UTC, merged