C18780 lab12
UCR-Paraiso-Lenguajes/lenguajes24 pull request #302
Opened 2024-05-29 23:46 UTC by JeanZQ

2024-05-30 14:27 UTC, cguillencr reviewed
Me parece interesante el enfoque del cookie. Sin embargo, creo que cuando el token y el cookie expiran el browser solo no va a enviar el cookie en el request, pero siempre va a ejecutar el request el cúal va a dar http-502. Para evitar esto tenes que revisar proactivamente la expieración de token antes de hacer cualquier request

2024-05-30 14:27 UTC, cguillencr commented on .github/workflows/C18780.yml
> +    branches: [ "DevOps_C18780" ]
solo carnet

2024-05-30 14:27 UTC, cguillencr commented on C18780/primer_trabajo/demo6/nextjs-dashboard/app/api/http.auth.ts
> +        console.log("Fallo login");
quitar logs

2024-05-30 14:27 UTC, cguillencr commented on C18780/primer_trabajo/demo6/nextjs-dashboard/app/login/page.tsx
> +            alert('Invalid username or password');
quitar losg y alerts

2024-06-03 21:23 UTC, cguillencr requested changes

2024-06-03 22:21 UTC, JeanZQ commented on .github/workflows/C18780.yml
> +          name varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
que raro esos create ya no deberian de salir
 https://github.com/UCR-Paraiso-Lenguajes/lenguajes24/blob/C18780_Lab9/.github/workflows/C18780.yml

2024-06-23 18:53 UTC, closed without merging