Lab12 c28223
UCR-Paraiso-Lenguajes/lenguajes24 pull request #305
Opened 2024-05-31 17:31 UTC by bulan506

2024-06-01 15:11 UTC, cguillencr requested changes
Quita todos los debug y bin para revisar menos

2024-06-01 15:11 UTC, cguillencr commented on C28223/Examen1_C28223/README.md
Este REadmE va en la Raiz de tu carnet en el repo

2024-06-01 15:11 UTC, cguillencr commented on C28223/Examen1_C28223/UT/bin/Debug/net8.0/Core.dll
los bin no ser versionan

2024-06-01 15:11 UTC, cguillencr commented on C28223/Examen1_C28223/UT/bin/Debug/net8.0/UT.runtimeconfig.json
no se versiona

2024-06-01 18:33 UTC, bulan506 commented on C28223/Examen1_C28223/Core/Models/Data/Products.cs
> +        public IEnumerable<Product> GetProductsByCategoryIDs(List<int> categoryIds)
la validación existe en al siguiente linea.

2024-06-01 18:34 UTC, bulan506 commented on C28223/Examen1_C28223/Core/Models/Data/Products.cs
> +        public IEnumerable<Product> SearchByTextAndCategory(string searchText, List<int> categoryIds)
la validaciones existen en al siguiente linea.

2024-06-01 19:10 UTC, bulan506 commented on C28223/Examen1_C28223/Core/Models/Store.cs
> +        public async Task<IEnumerable<Product>> getProductosCategoryID(List<int> categoryIDs)
la validaciones existen en al siguiente linea.

2024-06-03 21:12 UTC, cguillencr requested changes

2024-06-03 21:12 UTC, cguillencr commented on C28223/README.md
> +[![Packets-Project.jpg](https://i.postimg.cc/Y0JySL8Y/Packets-Project.jpg)](https://postimg.cc/T5Jc7wz3)
imagenes dentro de este repo

2024-06-06 01:27 UTC, cguillencr approved these changes

2024-06-08 20:07 UTC, merged