Lab13 B66958
UCR-Paraiso-Lenguajes/lenguajes24 pull request #317
Opened 2024-06-06 02:06 UTC by EisenheimDiego

2024-06-06 14:28 UTC, cguillencr requested changes

2024-06-06 14:28 UTC, cguillencr commented on B66958/Labs/Lab7/Core/Data/Db.cs
> +            "CREATE TABLE products (id CHAR(36) PRIMARY KEY, name VARCHAR(100), description VARCHAR(255), "
https://www.educba.com/sql-blob/

2024-06-06 14:28 UTC, cguillencr commented on B66958/Labs/Lab7/Core/Data/ProductData.cs
> +    internal async Task<Product> InsertProductAsync(Product product, ProductBusiness.OnNewProduct onNewProduct)
Hace que ProductBusiness.OnNewProduct onNewProduct sea opcional para no tener que pasarla siempre

2024-06-06 14:28 UTC, cguillencr commented on B66958/Labs/ejemploNext/my-nextjs-app/src/app/Admin/init/products.tsx
> +                console.log(createdProduct);
quitar logs

2024-06-16 22:08 UTC, EisenheimDiego commented on B66958/Labs/Lab7/Core/Data/Db.cs
> +            "CREATE TABLE products (id CHAR(36) PRIMARY KEY, name VARCHAR(100), description VARCHAR(255), "
Se cambió por VARBINARY, el equivalente de blob en SQLServer.

2024-06-16 22:09 UTC, EisenheimDiego commented on B66958/Labs/Lab7/Core/Data/ProductData.cs
> +    internal async Task<Product> InsertProductAsync(Product product, ProductBusiness.OnNewProduct onNewProduct)
Le puse valor null por defecto para que sea opcional.

2024-06-16 22:09 UTC, EisenheimDiego commented on B66958/Labs/ejemploNext/my-nextjs-app/src/app/Admin/init/products.tsx
> +                console.log(createdProduct);
Se me fue JAJA, listo.

2024-06-17 17:04 UTC, cguillencr approved these changes

2024-06-19 20:17 UTC, merged