Lab13 c12599
UCR-Paraiso-Lenguajes/lenguajes24 pull request #320
Opened 2024-06-17 03:49 UTC by Marianoda20027

2024-06-17 20:18 UTC, cguillencr requested changes

2024-06-17 20:18 UTC, cguillencr commented on C12599/Examen1/Api/Core/Database/StoreDB.cs
> +        public static void InsertProducts(List<Product> products)
falta el delegate

2024-06-18 17:36 UTC, cguillencr requested changes

2024-06-18 17:36 UTC, cguillencr commented on C12599/Examen1/laboratorio6/laboratorio6/app/admin/init/page.tsx
> +<<<<<<< HEAD
mal merge

2024-06-18 17:36 UTC, cguillencr commented on C12599/Examen1/laboratorio6/laboratorio6/app/admin/page.tsx
> +<<<<<<< HEAD
mal merge

2024-06-18 17:36 UTC, cguillencr commented on C12599/Examen1/laboratorio6/laboratorio6/app/products/insertproducts/page.tsx
> +        const response = await fetch('https://localhost:7043/api/InsertProducts', {
esta url deberia venir de los settings o variable de ambiente

2024-06-19 02:32 UTC, cguillencr requested changes

2024-06-19 02:32 UTC, cguillencr commented on C12599/Examen1/Api/Core/Bussisnes/InsertProductsLogic.cs
> +        public List<Product> InsertProduct(Product product)
podrias cargar el InsertProductDelegate por parametro ?

2024-06-19 04:09 UTC, Marianoda20027 commented on C12599/Examen1/Api/Core/Bussisnes/InsertProductsLogic.cs
> +        public List<Product> InsertProduct(Product product)
Esque ese es el encargado de cargar en la base de datos entonces si se hiciera por parametro tengo que establecer la conexion cada ves que hago un objeto y ahi nada mas tendria que llamar al metodo

2024-06-19 15:43 UTC, cguillencr approved these changes

2024-06-19 20:17 UTC, merged