Lab13 c22037
UCR-Paraiso-Lenguajes/lenguajes24 pull request #325
Opened 2024-06-18 06:17 UTC by ItsChaco26

2024-06-18 17:36 UTC, cguillencr commented on C22037/Lab12/Core/Database/SaleDB.cs
> +            List<WeeklyReport> weeklySales = await weeklySalesTask;
cambiar con un task.WaitAll

2024-06-19 02:15 UTC, cguillencr requested changes

2024-06-19 02:15 UTC, cguillencr commented on C22037/Lab12/Core/Database/SaleDB.cs
> +            List<WeeklyReport> weeklySales = await weeklySalesTask;
aun pendiente

2024-06-19 02:15 UTC, cguillencr commented on C22037/Lab12/page.tsx
> +            const response = await fetch(`https://localhost:7067/api/sale?date=${formattedDate}`, {
Esta url deberia venir de variable

2024-06-19 02:15 UTC, cguillencr commented on C22037/Lab12/page.tsx
> +            const response = await fetch('https://localhost:7067/api/store/products', {
igual a esta

2024-06-19 02:15 UTC, cguillencr commented on C22037/Lab12/page.tsx
> +            const response = await fetch('https://localhost:7067/api/store/products', {
igual a esta

2024-06-19 02:28 UTC, cguillencr requested changes

2024-06-19 02:28 UTC, cguillencr commented on C22037/Lab12/Core/Database/StoreDB.cs
> +    public async Task InsertProductAsync(ProductAdd product)
aqui no deberia ir el delegate ?

2024-06-19 03:12 UTC, ItsChaco26 commented on C22037/Lab12/Core/Database/StoreDB.cs
> +    public async Task InsertProductAsync(ProductAdd product)
Profe lo llama abajo

2024-06-19 19:14 UTC, merged