Inv_C22037
UCR-Paraiso-Lenguajes/lenguajes24 pull request #369
Opened 2024-06-22 23:38 UTC by ItsChaco26

2024-06-24 14:40 UTC, cguillencr requested changes

2024-06-24 14:40 UTC, cguillencr commented on C22037/Lab12/TodoApi/Hubs/ChatHub.cs
> +    public class ChatHub : Hub
Este nombre no refleja las campañas

2024-06-24 14:40 UTC, cguillencr commented on C22037/Lab12/TodoApi/Program.cs
> +    endpoints.MapHub<ChatHub>("/chatHub");
Este nombre no refleja las campañas

2024-06-24 14:40 UTC, cguillencr commented on C22037/Lab12/my-app/app/admin/init/page.tsx
> +            .withUrl("http://localhost:5087/chatHub")
Este nombre no refleja las campañas

2024-06-24 14:40 UTC, cguillencr commented on C22037/Lab12/my-app/app/admin/init/page.tsx
> +            .then(() => console.log('Connected to the campaign hub'))
quitar los console logs

2024-06-24 14:40 UTC, cguillencr commented on C22037/Lab12/my-app/app/page.tsx
> +      .withUrl("http://localhost:5087/chatHub")
Este nombre no refleja las campañas

2024-06-24 14:40 UTC, cguillencr commented on C22037/Lab12/my-app/app/page.tsx
> +        console.log("Connection to SignalR hub established");
quitarlos console logs

2024-06-25 20:17 UTC, cguillencr requested changes
Todo lo que retorne Task el nombre debe decir Async al final

2024-06-25 20:18 UTC, cguillencr reviewed
Falta el update de mensage para hacerel borrado lógico

2024-06-26 22:27 UTC, ItsChaco26 commented
> Falta el update de mensage para hacerel borrado lógico

2024-06-27 16:26 UTC, merged