Lab13 C22202 branch correcto y correcciones
UCR-Paraiso-Lenguajes/lenguajes24 pull request #370
Opened 2024-06-23 03:11 UTC by GaCha22

2024-06-24 14:37 UTC, cguillencr requested changes

2024-06-24 14:37 UTC, cguillencr commented on C22202/Lab7/Core/Business/ProductsLogic.cs
> +    public int Compare(Product? x, Product? y)
para que se necesita este compare ?

2024-06-24 14:37 UTC, cguillencr commented on C22202/Lab7/ShopApi/Controllers/AdminController.cs
> +            ProductsLogic.Instance.addProduct(product);
aqui falta el delegate, no ?

2024-06-24 20:44 UTC, GaCha22 commented on C22202/Lab7/Core/Business/ProductsLogic.cs
> +    public int Compare(Product? x, Product? y)
Este metodo se necesita para el buscador. Ya estaba desde antes, no sé porqué se agregó en ese commit si yo no le toqué nada

2024-06-24 20:45 UTC, GaCha22 commented on C22202/Lab7/ShopApi/Controllers/AdminController.cs
> +            ProductsLogic.Instance.addProduct(product);
El delegate está dentro de ese método

2024-06-25 20:12 UTC, cguillencr requested changes

2024-06-25 20:12 UTC, cguillencr commented on C22202/Lab7/Core/DB/ProductDB.cs
> +    public static void insertProduct(Product product, Action<Product> value)
debe ser async

2024-06-27 16:25 UTC, cguillencr requested changes

2024-06-27 16:25 UTC, cguillencr commented on C22202/Lab7/Core/Business/ProductsLogic.cs
> +    private Dictionary<int, List<Product>> productsDictionary { get; }
Ienumerable

2024-06-27 16:25 UTC, cguillencr commented on C22202/lab6/app/(admin)/admin/products/page.js
> +            // console.error(error);
qiutar comments

2024-06-27 16:25 UTC, cguillencr commented on C22202/lab6/app/(admin)/admin/products/page.js
> +        console.log(formData)
quitar console logs

2024-06-28 02:52 UTC, GaCha22 commented on C22202/Lab7/Core/Business/ProductsLogic.cs
> +    private Dictionary<int, List<Product>> productsDictionary { get; }
Profe, este diccionario no lo puedo pasar a IEnumerable, es el diccionario que filtra los productos por la categoría

2024-06-28 17:23 UTC, cguillencr requested changes

2024-06-28 17:23 UTC, cguillencr commented on C22202/Lab7/Core/DB/ProductDB.cs
> +    public static async void insertProduct(Product product, Action<Product> value)
todo esto debería ser Async

2024-07-01 08:35 UTC, GaCha22 commented on C22202/Lab7/Core/DB/ProductDB.cs
> +    public static async void insertProduct(Product product, Action<Product> value)
Profe, pero ya es async

2024-07-02 15:10 UTC, cguillencr requested changes

2024-07-02 15:10 UTC, cguillencr commented on C22202/Lab7/Core/DB/ProductDB.cs
> +    public static async void insertProduct(Product product, Action<Product> value)
1. Debe renombrarlo de insertProduct a insertProductAsync
2. NO hasta puesto el async en connection.Open();
3. ni aquí connection.BeginTransaction()
4. ni aquí  transaction.Commit();
5. ni aquí transaction.Rollback();

2024-07-05 10:47 UTC, closed without merging