C18780 investigacion
UCR-Paraiso-Lenguajes/lenguajes24 pull request #373
Opened 2024-06-24 20:25 UTC by JeanZQ

2024-06-25 20:11 UTC, cguillencr requested changes

2024-06-25 20:11 UTC, cguillencr commented on C18780/backend/StoreApi/Api/Controllers/AdController.cs
> +        private readonly IHubContext<ChatHub> _hubContext;
Renombrar chat

2024-06-25 20:11 UTC, cguillencr commented on C18780/backend/StoreApi/Hubs/ChatHub.cs
> +public class ChatHub : Hub
poner un nombre apropiado

2024-06-25 20:11 UTC, cguillencr commented on C18780/backend/StoreApi/Program.cs
> +//builder.Services.AddCors(p => p.AddPolicy("corsapp", builder =>
quitar código comentado

2024-06-25 20:20 UTC, cguillencr requested changes
No veo los metodos para insertar / borar en la bd

2024-06-27 01:18 UTC, JeanZQ commented on C18780/backend/StoreApi/Program.cs
> +//builder.Services.AddCors(p => p.AddPolicy("corsapp", builder =>
Listo

2024-06-27 01:20 UTC, JeanZQ commented on C18780/backend/StoreApi/Hubs/ChatHub.cs
> +public class ChatHub : Hub
Profe que nombre le puedo poner? es que yo le puse ese nombre porque en el tutorial de microsoft dice que lo hiciera.

2024-06-27 01:21 UTC, JeanZQ commented on C18780/backend/StoreApi/Api/Controllers/AdController.cs
> +        private readonly IHubContext<ChatHub> _hubContext;
Profe que nombre le puedo poner? es que yo le puse ese nombre porque en el tutorial de microsoft dice que lo ponga asi.

2024-06-27 04:12 UTC, cguillencr commented on C18780/backend/StoreApi/Api/Controllers/AdController.cs
> +        private readonly IHubContext<ChatHub> _hubContext;
Campañas hub

2024-06-27 04:13 UTC, cguillencr commented on C18780/backend/StoreApi/Hubs/ChatHub.cs
> +public class ChatHub : Hub
se le pone un nombre relacion con le problema que se esta resolviendo

2024-06-28 01:58 UTC, JeanZQ commented on C18780/backend/StoreApi/Api/Controllers/AdController.cs
> +        private readonly IHubContext<ChatHub> _hubContext;
listo

2024-06-28 01:58 UTC, JeanZQ commented on C18780/backend/StoreApi/Hubs/ChatHub.cs
> +public class ChatHub : Hub
listo

2024-06-28 17:24 UTC, cguillencr approved these changes

2024-06-28 17:24 UTC, merged